### ISSUE TITLE
Install file

### ISSUE THREAD

**Issue by ChickenGoddess** [ThauEx/ffrk-proxy#53] opened 2016-06-07 03:21 UTC
The start batch file is easily viewable, but I am unable to find the install file for the program. Has it been removed?

**Comment by ThauEx** [comment] 2016-06-07 04:04
Go to the release page an pick a release there. I had to do this, because of the dependencies.

**Comment by leojreimroc** [comment] 2016-06-07 13:21
I have the same issue actually.  I went on the release page, and it's the same files.  Still can't seem to find the install.bat.  Were you able to solve the issue ChickenGoddess?

**Comment by ThauEx** [comment] 2016-06-07 13:40
There is no `install.bat` because nodejs is included in the release.

**Comment by leojreimroc** [comment] 2016-06-07 14:58
Thanks for the reply.  I was actually getting the following error when opening start.bat  Fixed it by downloading the files on the release page.  The front page files didn't have the \bin\node.exe

'bin\node.exe' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by leojreimroc** [comment] 2016-06-07 15:01
Just getting a slight issue with the root certificate work work (rootCA.pem?).  It's asking for a password when I open it.  Do I set this password anywhere?  When I input anything, it says incorrect password.

**Comment by ThauEx** [comment] 2016-06-07 15:09
The password should be your phones pin, you have to set one in order to install a custom root ca.

**Comment by leojreimroc** [comment] 2016-06-07 15:22
I'm assuming you mean the lock screen pin?  I just set a basic 4 digit pin.  Still wouldn't let me install the certificate.  I'm getting the same error as before.  I tried rebooting the phone (you never know).  I also tried installing the certificate from the Settings under Credential storage\Install from device storage.

**Comment by leojreimroc** [comment] 2016-06-07 15:44
I sure can.  Thanks again for your time by the way.

![screenshot_2016-06-07-12-39-07 1](https://cloud.githubusercontent.com/assets/19799777/15864421/6cab5a76-2cad-11e6-82ee-c99ed8a069e0.png)
![screenshot_2016-06-07-12-39-14 1](https://cloud.githubusercontent.com/assets/19799777/15864436/7bbb2e7e-2cad-11e6-9d7f-77581c731e98.png)
![screenshot_2016-06-07-12-40-30 1](https://cloud.githubusercontent.com/assets/19799777/15864451/91e75aba-2cad-11e6-972f-78fabf2bed8a.png)
![screenshot_2016-06-07-12-40-34 1](https://cloud.githubusercontent.com/assets/19799777/15864457/9dbaacc0-2cad-11e6-93d1-a1ee6f986e3d.png)

**Comment by KHShadowrunner** [comment] 2016-06-07 16:11
Are you installing it as a VPN cert instead of a WiFi cert?

**Comment by leojreimroc** [comment] 2016-06-07 16:14
Sorry, I should have mentioned that.  I did try both wifi and VPN/apps.  Pin is set to a simple 4 digit number if that matters.

**Comment by KHShadowrunner** [comment] 2016-06-07 16:26
Weird, yo ucould try temporarily changing your pin and trying again? Do you encrypt your device and does that use a different PW?

**Comment by leojreimroc** [comment] 2016-06-07 16:34
I'll give that a go tonight.  Had to go to work.  I'll let you know.

**Comment by leojreimroc** [comment] 2016-06-08 01:54
Back from work.  I tried a bunch of things.  I tried to put a password instead of a pin.  The error message changed. For a while, I got "credential storage cleared" as a response.  Now, I'm actually back to incorrect password.  Some googling brings up others with similar issues.  I'm going to keep searching for a solution.  Any ideas are appreciated of course.

**Comment by leojreimroc** [comment] 2016-06-08 03:17
Solution:  http://www.netsparkmobile.com/support/en/installation/109-credential-storage.html

I tried many similar things for a couple of hours actually.  There were many different solutions online, but the above worked for me.  Everything works fine now.

**Comment by ThauEx** [comment] 2016-06-08 06:50
Wow, nice android bug...
SInce the issue is resolved, I will close this it.

**Closed by ThauEx** 2016-06-08 06:50 UTC
